spring.application.name=study-bbs

server.port=${PORT:8080}

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

mybatis.mapper-locations=classpath:/mapper/**/*.xml

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

server.servlet.session.tracking-modes=cookie


# ================= DB =================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


# ================= KAKAO =================
custom.property.kakao-client-id=${KAKAO_CLIENT_ID}
custom.property.kakao-rest-key=${KAKAO_REST_KEY}
custom.property.kakao-redirect-uri=${KAKAO_REDIRECT_URI}
custom.property.kakao-logout-redirect-uri=${KAKAO_LOGOUT_REDIRECT_URI}


# ================= NAVER =================
custom.property.naver-client-id=${NAVER_CLIENT_ID}
custom.property.naver-client-secret=${NAVER_CLIENT_SECRET}
custom.property.naver-redirect-uri=${NAVER_REDIRECT_URI}


# ================= WEATHER =================
custom.property.weather-key=${WEATHER_KEY}
